---
title: "DLPFC"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

We will analyze all 12 slides

```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}
library("nnSVG")
library("scater")
library("scran")
library("scry")
library("SPARK")
library("harmony")
library("Seurat")
library("spatialLIBD")
library("KODAMA")
library("KODAMAextra")


sample_names=c("151507",
               "151508",
               "151509",
               "151510",
               "151669",
               "151670",
               "151671",
               "151672",
               "151673",
               "151674",
               "151675",
               "151676")

subject_names= c("Br5292","Br5595", "Br8100")

#spe <- fetch_data(type = 'spe',destdir="../Temporary")
load("../DLFPC.RData")

metaData = SingleCellExperiment::colData(spe)
expr = SingleCellExperiment::counts(spe)
sample_names <- paste0("sample_", unique(colData(spe)$sample_id))
sample_names <-  unique(colData(spe)$sample_id)
dim(spe)




```

 identify mitochondrial genes

```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}

is_mito <- grepl("(^MT-)|(^mt-)", rowData(spe)$gene_name)
table(is_mito)

```

 calculate per-spot QC metrics
 and select the QC threshoulds
```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}
spe <- addPerCellQC(spe, subsets = list(mito = is_mito))

# select QC thresholds
qc_lib_size <- colData(spe)$sum < 500
qc_detected <- colData(spe)$detected < 250
qc_mito <- colData(spe)$subsets_mito_percent > 30
qc_cell_count <- colData(spe)$cell_count > 12
```

Spot to discard and filter low-quality
```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}

discard <- qc_lib_size | qc_detected | qc_mito | qc_cell_count
table(discard)
colData(spe)$discard <- discard

spe <- spe[, !colData(spe)$discard]
dim(spe)

```

Horizontalization

```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}
# readjust xy
xy=spatialCoords(spe)
samples=unique(colData(spe)$sample_id)
for(j in 1:length(samples)){
  sel=samples[j]==colData(spe)$sample_id
  xy[sel,1]=spatialCoords(spe)[sel,1]+12000*(j-1)
}
spatialCoords(spe)=xy
```

Gene filtering
```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}

spe <- filter_genes(
  spe,
  filter_genes_ncounts = 2,   #ncounts
  filter_genes_pcspots = 0.5,
  filter_mito = TRUE
)

dim(spe)
```

REmove the spots that have not been manually assigned
```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}
sel= !is.na(colData(spe)$layer_guess_reordered)
spe = spe[,sel]
dim(spe)
```


 normalization
```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}
spe <- computeLibraryFactors(spe)
spe <- logNormCounts(spe)
```


Identification of the gene spatially relevvant

```{r, fig.width=10, fig.height=4}
gene_i=NULL
pvalue_i=NULL
pvalue_mat=matrix(nrow=nrow(spe),ncol=length(sample_names))
for(i in 1:length(sample_names)){
  sel=colData(spe)$sample_id==sample_names[i]
  spe_sub= spe[,sel]

  sparkX <- sparkx(logcounts(spe_sub),spatialCoords(spe_sub),numCores=1,option="mixture")

  gene_i=c(gene_i,rowData(spe)$gene_id)
  pvalue_i=c(pvalue_i,sparkX$res_mtest$combinedPval)
  pvalue_mat[,i]=sparkX$res_mtest$combinedPval
  print(sample_names[i])
}
oo=order(pvalue_i)
top_genes=gene_i[oo]
n=ave(1:length(top_genes), top_genes, FUN = seq_along)
top_genes=top_genes[n==1]

oo=order(apply(pvalue_mat,1,function(x) median(-log(x))),decreasing = TRUE)
top=gene_i[oo]
```



PCA and HARMONY

```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}

 data=t(logcounts(spe)[top[1:2000],])

 subjects=colData(spe)$subject
 dim(spe_sub)
 spe <- runPCA(spe, 50,subset_row = top[1:2000], scale=TRUE)

 #pca=irlba(scale(data),50)$u

 labels=as.factor(colData(spe)$layer_guess_reordered)
 xy=as.matrix(spatialCoords(spe))
 samples=colData(spe)$sample_id

 spe <- RunHarmony(spe, "subject",lambda=NULL)
# pca <- RunHarmony(pca, subjects,lambda=NULL)
 pca=reducedDim(spe,type = "HARMONY")[,1:50]
plot(pca)
```


KODAMA

```{r, fig.width=10, fig.height=4}

kk=KODAMA.matrix.parallel(pca,
                            spatial = xy,
                            FUN= "PLS" ,
                            landmarks = 100000,
                            splitting = 100,
                            f.par.pls = 50,
                            spatial.resolution = 0.4,
                            n.cores=4)

  print("KODAMA finished")
  
     config=umap.defaults
     config$n_threads = 4
     config$n_sgd_threads = "auto"
     kk_UMAP=KODAMA.visualization(kk,method="UMAP",config=config)

```

CLUSTER

```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}
library("mclust")

  clu=kmeans(kk_UMAP,7,nstart = 100)$cluster
  plot(kk_UMAP,col=labels,pch=20)
  plot(kk_UMAP,col=clu,pch=20)

plot(xy,col=clu,pch=20)

u=unique(samples)
for(i in 1:length(u)){
  sel=samples==u[i]
  print(adjustedRandIndex(labels[sel],clu[sel]))
}

ref=refine_SVM(xy,clu,samples,cost=100)

u=unique(samples)
for(i in 1:length(u)){
  sel=samples==u[i]
  print(adjustedRandIndex(labels[sel],ref[sel]))
}
plot(xy,col=ref,pch=20)

```



TRAJECTORY

```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}
library("slingshot")

d <- slingshot(kk_UMAP, clusterLabels = clu)
trajectory=d@metadata$curves$Lineage1$s
k=knn_Armadillo(trajectory,kk_UMAP,1)

map_color=rainbow(nrow(trajectory))[k$nn_index]
plot(kk_UMAP,col=map_color)




```




