---
title: "About"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

# Load necessary libraries
install.packages(c("Seurat", "SeuratData", "ggplot2", "patchwork", "dplyr", "KODAMA", "KODAMAextra"))

# Load the libraries
library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)
library(KODAMA)
library(KODAMAextra)
library(harmony)

# Install the data if necessary
InstallData("stxBrain")

# Load the data
brain <- LoadData("stxBrain", type = "anterior1")

# Initial visualization
plot1 <- VlnPlot(brain, features = "nCount_Spatial", pt.size = 0.1) + NoLegend()
plot2 <- SpatialFeaturePlot(brain, features = "nCount_Spatial") + theme(legend.position = "right")
wrap_plots(plot1, plot2)

# Pre-process the data
brain <- SCTransform(brain, assay = "Spatial", verbose = FALSE)
brain <- RunPCA(brain, assay = "SCT", verbose = FALSE)
brain <- FindNeighbors(brain, reduction = "pca", dims = 1:30)
brain <- FindClusters(brain, verbose = FALSE)
brain <- RunUMAP(brain, reduction = "pca", dims = 1:30)

# Visualization of PCA and UMAP results
p1 <- DimPlot(brain, reduction = "umap", label = TRUE)
p2 <- SpatialDimPlot(brain, label = TRUE, label.size = 3)
p1 + p2

# Visualization of clusters with SpatialDimPlot
SpatialDimPlot(brain, cells.highlight = CellsByIdentities(object = brain, idents = c(2, 1, 4, 3, 5, 8)), facet.highlight = TRUE, ncol = 3)

# Run and visualize KODAMA
brain <- RunKODAMAmatrix(brain, reduction = "pca")
brain <- RunKODAMAvisualization(brain, method = "UMAP", config = config)

# Visualization of KODAMA results with DimPlot and SpatialDimPlot
p3 <- DimPlot(spe, reduction = "kodama", label = TRUE)
p4 <- SpatialDimPlot(spe, label = TRUE, label.size = 3)
p3 + p4
