---
title: "About"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

# Introduction
Describe your project.


# Main simulation study
## Scenario 1

Bla bla.

```{r, fig.width=10, fig.height=4}

library("KODAMA")
library("KODAMAextra")
x1=runif(100,min=-1,max=0)
x2=runif(100,min=0,max=1)
y1=runif(100)
y2=runif(100)
x=c(x1,x2)
y=c(y1,y2)
xy=cbind(x,y)

labels=rep(c(TRUE,FALSE),each=100)
ss=sample(100,5)
labels[ss]=!labels[ss]
labels=labels
region=rep(1:0,each=100)

data=cbind(rnorm(200,mean=labels,sd=0.1),
           rnorm(200,mean=labels,sd=0.1))

color.code=c("#1d79d0aa","#53ca3eaa")



kk <- KODAMA.matrix.parallel(data,spatial=xy,spatial.resolution=0.1,M=100,
                      FUN="PLS",
                      landmarks = 100000,
                      splitting = 100,
                      f.par.pls =  2,
                      n.cores=4)

vis=RunKODAMAvisualization(kk,method="UMAP")

u=umap(data)$layout

par(mfrow=c(1,3))

plot(x,y,bg=color.code[region+1],pch=21+2*!labels,cex=1+1.5*region,axes=FALSE,main="Position")
axis(1)
axis(2,las=2)
box()

plot(vis,type="n",axes=FALSE,main="KODAMA")
axis(1)
axis(2,las=2)
box()
points(vis[!labels,],bg=color.code[region+1][!labels],pch=21+2,cex=1+1.5*region[!labels])
points(vis[labels,],bg=color.code[region+1][labels],pch=21+2*0,cex=1+1.5*region[labels])

plot(u,type="n",axes=FALSE,xlab="Dimension 1",ylab="Dimension 2",main="UMAP")
axis(1)
axis(2,las=2)
box()
points(u[!labels,],bg=color.code[region+1][!labels],pch=21+2,cex=1+1.5*region[!labels])
points(u[labels,],bg=color.code[region+1][labels],pch=21+2*0,cex=1+1.5*region[labels])
```


## Scenario 2

Bla bla.

```{r, fig.width=10, fig.height=4}

x1=runif(100,min=-1,max=0)
x2=runif(100,min=0,max=1)
y1=runif(100)
y2=runif(100)
x=c(x1,x2)
y=c(y1,y2)
xy=cbind(x,y)


labels=rep(c(TRUE,FALSE),each=100)

region=rep(1:0,each=100)

data=cbind(rnorm(200,mean=1+labels,sd=0.1),
           rnorm(200,mean=1+labels,sd=0.1),
           rnorm(200,mean=1+labels,sd=0.1),
           rnorm(200,mean=1+labels,sd=0.1))

ll=length(data)
ss=sample(ll,ll*0.5)
data[ss]=0
color.code=c("#1d79d0aa","#53ca3eaa")

sel=apply(data,1,function(x) sum(x>0))>2
data=data[sel,]
region=region[sel]
labels=labels[sel]
xy=xy[sel,]


labels=data>0
labels=labels[,1]+
  labels[,2]*2+
  labels[,3]*4+
  labels[,4]*8
labels=as.numeric(as.factor(labels))+1

pca=prcomp(scale(data))$x

kk <- KODAMA.matrix.parallel(pca,spatial=xy,spatial.resolution=0.1,M=100,
                             FUN="PLS",
                             landmarks = 100000,
                             splitting = 100,
                             f.par.pls =  10,
                             n.cores=4)
config=umap.defaults
config$n_neighbors=15
vis=RunKODAMAvisualization(kk,method="UMAP",config=config)

u=umap(pca)$layout
old.par = par(mfrow=c(1,3))



plot(xy,bg=labels,pch=21+2*(region),cex=2+1*region,axes=FALSE,main="Position")
axis(1)
axis(2,las=2)
box()

plot(vis,bg=labels,pch=21+2*(region),cex=1+1.5*region,axes=FALSE,main="KODAMA")
axis(1)
axis(2,las=2)
box()

plot(u,bg=labels,pch=21+2*(region),cex=1+1.5*region,axes=FALSE,main="UMAP")
axis(1)
axis(2,las=2)
box()
par(old.par)
```
